name: Preparant per producció
run-name: ${{ github.actor }} està pujant l'aplicació a PROD  🚀
on: [push]
jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      - name: Obtenint el codi del respositori
        uses: actions/checkout@v4

      - name: crear dist
        run: |
          cd ${{ github.workspace }}/gitactions/
          npm install
          npm run build

      - name: scp a produccio
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          cd ${{ github.workspace }}/gitactions/
          scp -r -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null -i "~/prod_key.pem" ./dist/* ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a16adrrodgon/web/github-action.a16adrrodgon.daw.inspedralbes.cat/public_html/
          
      - run: echo "🍏 This job's status is ${{ job.status }}."